### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m3-evaluacion-intermedia-luzagm#1]
Buen trabajo @luzagm!

Algunas pistas para acabarlo:

## React

- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] En los componentes de clase usa propTypes para comprobar el tipo de dato de las props
- [x] Usa el `id` de cada pokemon para el `key` de react cuando mapeas y creas un listado de componentes. También para los tipos.
- [ ] Mover `li` fuera del componente 'Pokemon', de esta manera es una tarjeta simple que podemos usar en cualquier lugar, no solo dentro de un 'ul` (opcional)
- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: los tipos tienen que ser una lista, no pueden ser h3 sueltos, recuerda que son elementos relacionados. Un OL o UL es lo suyo.

## HTML

- [ ] Revise los metadatos en index.html (lang, title ...)

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by luzagm** [comment]
En el punto 4 me dices que coloque los tipos de los pokemon en una lista y no en h3, pero están en una lista ya, ¿no?

**Comment by luzagm** [comment]
He añadido lo de las propTypes, pero no sé si está en el lugar correcto...

**Comment by luzagm** [comment]
Me gustaría revisarla parte de HTML que me indicas luego si se puede, porque no tengo muy claras cómo hacer algunas cosas :S

**Comment by migueldelmazo** [comment]
> En el punto 4 me dices que coloque los tipos de los pokemon en una lista y no en h3, pero están en una lista ya, ¿no?
Tienes más razón que una santa, me he equivocado.

**Comment by migueldelmazo** [comment]
> He añadido lo de las propTypes, pero no sé si está en el lugar correcto...

Están en el sitio correcto, pero supongo que esta línea no está bien https://github.com/Adalab/m3-evaluacion-intermedia-luzagm/blob/master/src/components/Pokemon.js#L33 ya que `pokemonType` no es un string, es un array.

Y nos faltaría otro para `pokemonImage`.

También te digo que eres de las pocas personas que se ha currado los propTypes, así que muy bien hecho!!!

**Comment by migueldelmazo** [comment]
> Me gustaría revisarla parte de HTML que me indicas luego si se puede, porque no tengo muy claras cómo hacer algunas cosas :S

Cuando quieras lo vemos en clase!
